#!/bin/bash

if [ -n "$ROOFITSYS" ]
    then
    echo set ROOFIT
    roofitflags="-I$ROOFITSYS/include -L$ROOFITSYS/lib"
fi

rooflags="$roofitflags `root-config --cflags --libs` -lRooFit -lRooFitCore -lRooStats -lMathMore -lMinuit  -lFoam"
echo g++ -o extractLimitLands $rooflags extractLimitLands.cc
g++ -o extractLimitLands $rooflags extractLimitLands.cc
g++ -o runRa7LimitLands $rooflags runRa7LimitLands.cc
g++ -o makeExclusions $rooflags makeExclusions.C
