#!/bin/env python
import sys
import string
if len(sys.argv) < 3:
    print 'Usage:', sys.argv[0], '<input data file> <output data file>'
else:    
    lines = open (sys.argv[1],'r')
    out = open (sys.argv[2], 'w')
    out.write('lumi 9200 368\n')
    for line in lines:
        if line[0] == '#':
            out.write (line)
        else:
            tokens = string.split (line);
            out.write ('data ')
            for token in tokens: out.write (token+' ')
            out.write ('\n')
