#!/bin/env python
import sys
import string
if len(sys.argv) < 3:
    print 'Usage:', sys.argv[0], '<input data file> <output data file>'
else:    
    lines = open (sys.argv[1],'r')
    out = open (sys.argv[2], 'w')
    out.write ('xsec ')
    for line in lines: out.write (line)
